import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Clone Boldo</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      {/* Header */}
      <div className='bg-[#0A2640] h-screen w-full font-sans'>
        <div className='flex  flex-row justify-between px-[5rem] pt-[3rem]'>
          <div className='flex w-[6rem] h-[2rem]'>
            <img src='logo/lg-boldo.png' alt='logo' />
            <img src='logo/lg-boldoshape.png' alt='logo' />
          </div>
          <div>
            <a href='' className='text-white px-6 text-[23px] font-medium'>
              Product
            </a>
            <a href='' className='text-white px-6 text-[23px] font-medium'>
              Services
            </a>
            <a href='' className='text-white px-6 text-[23px] font-medium'>
              About
            </a>
            <a
              href=''
              className='bg-white px-10 py-2 text-[#0A2640] font-bold text-[23px] rounded-xl'
            >
              Log In
            </a>
          </div>
        </div>

        <div className='flex justify-center pt-[10rem]'>
          <div className='flex flex-wrap max-w-[80%] flex-row justify-center'>
            <div className='flex flex-col justify-start w-[50%]'>
              <h2 className='text-white text-[40px] font-semibold'>
                Save time by building fast with Boldo Template
              </h2>
              <p className='text-white py-[15px]'>
                Funding handshake buyer business-to-business metrics iPad
                partnership. First mover advantage innovator success deployment
                non-disclosure.
              </p>
              <div>
                <button className='px-5 bg-[#69E6A6] py-2 text-[#0A2640] font-bold mr-5 rounded-lg'>
                  Buy Tamplate
                </button>
                <button className='px-10 text-white border-2 border-white border-solid py-2 rounded-lg font-bold'>
                  Explore
                </button>
              </div>
            </div>
            <div className='w-[30%]'>
              <div className='flex  flex-row w[100%]'>
                <img src='/img-content.png' alt='' className='w-[100%]' />
              </div>
              <div className='flex flex-row  pt-10 w-[100%]'>
                <img src='/img-content.png' alt='' className='w-[50%]' />
                <img src='/img-content2.png' alt='' className='w-[50%] pl-5' />
              </div>
            </div>
          </div>
        </div>

        <div className='flex justify-center'>
          <div className='absolute bottom-10'>
            <div className='flex flex-row justify-center'>
              <img src='logo/lg-presto.png' alt='' className='px-6' />
              <img src='logo/lg-boldo-white.png' alt='' className='px-6' />
              <img src='logo/lg-presto.png' alt='' className='px-6' />
              <img src='logo/lg-boldo-white.png' alt='' className='px-6' />
              <img src='logo/lg-presto.png' alt='' className='px-6' />
            </div>
          </div>
        </div>
      </div>

      {/*  */}
      <div className=' h-[110vh] w-full px-[5rem]'>
        <div className='flex justify-center pt-10'>
          <div className='flex flex-col text-center  max-w-[60%]'>
            <span className=' text-gray-600'>Our Services</span>
            <span className='text-[45px] pt-1'>
              Handshake infographic mass market crowdfunding iteration.
            </span>
          </div>
        </div>
        <div className='pt-16 flex flex-row justify-center '>
          <div className='w-[300px] h-[520px] mx-[55px]  rounded-xl relative'>
            <img src='content/vektor01.png' alt='' />
            <h4 className='text-[22px] py-2 font-semibold'>
              Cool feature title
            </h4>
            <span className='text-gray-700 text-[20px] '>
              Learning curve network effects return on investment.
            </span>
            <div className='py-2 absolute bottom-1 border-b-4 border-gray-600 '>
              <a href='' className='text-[20px] text-[#0A2640] font-bold '>
                Explore Page
              </a>
            </div>
          </div>
          <div className='w-[300px] h-[520px] mx-[55px]  rounded-xl relative'>
            <img src='content/vektor02.png' alt='' />
            <h4 className='text-[22px] py-2 font-semibold'>
              Cool feature title
            </h4>
            <span className='text-gray-700 text-[20px] '>
              Learning curve network effects return on investment.
            </span>
            <div className='py-2 absolute bottom-1 border-b-4 border-gray-600 '>
              <a href='' className='text-[20px] text-[#0A2640] font-bold '>
                Explore Page
              </a>
            </div>
          </div>
          <div className='w-[300px] h-[520px] mx-[55px]  rounded-xl relative'>
            <img src='content/vektor03.png' alt='' />
            <h4 className='text-[22px] py-2 font-semibold'>
              Cool feature title
            </h4>
            <span className='text-gray-700 text-[20px] '>
              Learning curve network effects return on investment.
            </span>
            <div className='py-2 absolute bottom-1 border-b-4 border-gray-600 '>
              <a href='' className='text-[20px] text-[#0A2640] font-bold '>
                Explore Page
              </a>
            </div>
          </div>
        </div>
      </div>

      {/*  */}
      <div className='h-screen w-full px-[5rem] pt-[4rem]'>
        <div className='flex flex-row justify-center '>
          <div className='w-[80%] flex flex-row '>
            <div className='mr-10 relative  w-[50%]'>
              <img src='content/people01.png' alt='' />
              <div className='absolute mt-[-300px] right-10'>
                <img src='content/income.png' alt='' />
              </div>
            </div>
            <div className='w-[50%] relative'>
              <h3 className='text-[40px]'>
                We connect our customers with the best, and help them keep
                up-and stay open.
              </h3>
              <ul className='pt-10 list-disc pl-[20px]'>
                <li className='text-[20px] py-1'>
                  We connect our customers with the best.
                </li>
                <li className='text-[20px] py-1'>
                  Advisor success customer launch party.
                </li>
                <li className='text-[20px] py-1'>
                  Business-to-consumer long tail.
                </li>
              </ul>
              <div className='absolute bottom-3 py-3 px-8 bg-[#0A2640] w-[10rem] rounded-xl  text-center hover:opacity-90'>
                <button className='text-white font-semibold '>Start Now</button>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/*  */}
      <div className='h-screen w-full px-[5rem] pt-[4rem]'>
        <div className='flex flex-row justify-center '>
          <div className='w-[80%] flex flex-row '>
            <div className='w-[50%] relative'>
              <h3 className='text-[40px]'>
                We connect our customers with the best, and help them keep
                up-and stay open.
              </h3>
              <ul className='pt-10 '>
                <li className='text-[20px] py-3 px-4 text-white rounded-lg font-medium  mb-6 w-[85%] bg-[#0A2640] shadow-md flex '>
                  <span className='pr-4'>
                    <img src='logo/ic-flower.png' alt='' />
                  </span>
                  We connect our customers with the best.
                </li>
                <li className='text-[20px] py-3 px-4 text-[#0A2640] rounded-lg shadow-md font-medium  mb-6 w-[85%] bg-white flex '>
                  <span className='pr-4'>
                    <img src='logo/ic-eye.png' alt='' />
                  </span>
                  Advisor success customer launch party.
                </li>
                <li className='text-[20px] py-3 px-4 text-[#0A2640] rounded-lg shadow-md font-medium  mb-6 w-[85%] bg-white flex '>
                  <span className='pr-4'>
                    <img src='logo/ic-sun.png' alt='' />
                  </span>
                  Business-to-consumer long tail.
                </li>
              </ul>
            </div>
            <div className='mr-10 relative  w-[50%]'>
              <img src='content/people02.png' alt='' />
              <div className='absolute mt-[-300px] left-5'>
                <img src='content/income02.png' alt='' />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
